# ==============================================================================
# Web3 Indexer - Production-Grade GolangCI-Lint Configuration
# Target: 6 nines reliability with automated quality gates
# ==============================================================================

# Linters enabled for Web3 production standards
linters:
  disable-all: true
  enable:
    # --- Essential Go Checks ---
    - gofmt          # Code formatting (non-negotiable)
    - govet          # Go vet static analysis (bug detection)
    - errcheck       # ALL errors must be checked (no `_ = func()`)
    - staticcheck    # Go static analysis (finds bugs & issues)

    # --- Web3 Critical ---
    - bodyclose      # Ensure HTTP/RPC bodies closed (memory leak prevention)
    - errchkjson     # Check JSON encoding/decoding errors
    - noctx          # Ensure context propagation (cancellation & timeout)
    - sqlclosecheck  # Ensure sql.Rows/Stmt closed (DB resource leak)

    # --- Code Quality (relaxed for demo) ---
    - goconst        # Detect repeated strings that could be constants
    - gocritic       # Find code patterns needing improvement
    - gocyclo        # Cyclomatic complexity (limit: 25)
    - revive         # Fast, configurable linter (modern golint replacement)

    # --- Style & Best Practices ---
    - gosimple       # Simplify code (finds unnecessary complexity)
    - ineffassign    # Detect ineffectual assignments
    - misspell       # Catch commonly misspelled English words
    - prealloc       # Pre-allocate slices for performance
    - unconvert      # Detect unnecessary type conversions

    # --- Security ---
    - gosec          # Security audit (hardcoded keys, SQL injection, etc.)

    # --- Code Quality ---
    - goconst        # Detect repeated strings that could be constants
    - gocritic       # Find code patterns needing improvement
    - gocyclo        # Cyclomatic complexity (limit: 15)
    - revive         # Fast, configurable linter (modern golint replacement)

    # --- Style & Best Practices ---
    - gosimple       # Simplify code (find unnecessary complexity)
    - ineffassign    # Detect ineffectual assignments
    - misspell       # Catch commonly misspelled English words
    - prealloc       # Pre-allocate slices for performance
    - unconvert      # Detect unnecessary type conversions
    - unparam        # Detect unused function parameters

    # --- Security ---
    - gosec          # Security audit (hardcoded keys, SQL injection, etc.)

    # --- Disabled for demo project (too strict) ---
    # - fieldalignment # Struct field alignment (disabled for demo)
    # - unused        # Detect unused code (disabled for demo)

linters-settings:
  # Cyclomatic complexity limit (highly complex functions are bugs)
  gocyclo:
    min-complexity: 25  # Increased for demo project

  # Skip main files for errcheck (common in CLI apps)
  errcheck:
    check-type-assertions: true
    check-blank: true
    # Ignore common patterns in demo code
    exclude-functions:
      - (io.Closer).Close
      - (*github.com/ethereum/go-ethereum/ethclient.Client).Close
      - (*github.com/gorilla/websocket.Conn).Close
      - (*github.com/gorilla/websocket.Conn).SetReadDeadline
      - (*github.com/gorilla/websocket.Conn).SetWriteDeadline
      - (*github.com/gorilla/websocket.Conn).WriteMessage
      - (net/http.ResponseWriter).Write
      - .Write
      - fmt.Sprintf
      - fmt.Fprintf
      - (net/http.ResponseWriter).Write

  # Detect repeated strings that should be constants
  goconst:
    min-len: 3
    min-occurrences: 3

  # Enable all gocritic checks (advanced diagnostics)
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

  # Revive configuration (modern golint)
  revive:
    confidence: 0.8
    rules:
      - name: exported
        severity: warning
      - name: var-naming
        severity: warning
      - name: blank-imports
        severity: warning
      - name: context-as-argument
        severity: warning
      - name: context-keys-type
        severity: warning
      - name: dot-imports
        severity: warning
      - name: error-return
        severity: warning
      - name: error-strings
        severity: warning
      - name: error-naming
        severity: warning
      - name: if-return
        severity: warning
      - name: increment-decrement
        severity: warning
      - name: var-declaration
        severity: warning
      - name: package-comments
        severity: warning
      - name: range
        severity: warning
      - name: receiver-naming
        severity: warning
      - name: time-naming
        severity: warning
      - name: unexported-return
        severity: warning
      - name: indent-error-flow
        severity: warning
      - name: errorf
        severity: warning
      - name: empty-block
        severity: warning
      - name: superfluous-else
        severity: warning
      - name: unused-parameter
        severity: warning
      - name: unreachable-code
        severity: warning
      - name: redefines-builtin-id
        severity: warning

  # GoSec security settings
  gosec:
    excludes:
      - G104  # Allow errcheck to handle unchecked errors
    config:
      G101: # Look for hard-coded credentials
        pattern: "(?i)(passwd|password|pwd|secret|api-key|apikey|api_key)"
      G102: # Bind to all interfaces
        no-ssh-host: true

  # govet settings
  govet:
    enable-all: true
    disable:
      - shadow  # Can be noisy, but worth enabling in strict mode
      - fieldalignment

# Run configuration
run:
  # Timeout for analysis
  timeout: 5m

  # Build tags
  build-tags:
    - integration

  # Go version to use
  go: "1.21"

# Issues configuration
issues:
  # Maximum issues count per one linter
  max-issues-per-linter: 0

  # Which dirs to exclude from analysis
  exclude-dirs:
    - vendor
    - third_party
    - testdata
    - .git
    - .github
    - scripts
    - tools

  # Which files to exclude from analysis
  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*\\.gen\\.go$"

  # Exclude specific issues for demo project
  exclude-rules: []

# Output configuration
output:
  # Formats for output
  formats:
    - format: colored-line-number
